class AppStrings {
  static const Map<String, Map<String, String>> _translations = {
    'ar': {
      'app_name': 'LOVERS',
      'tagline': 'تواصل بلا حدود',
      'login_google': 'تسجيل الدخول بواسطة Google',
      'login_phone': 'الهاتف',
      'login_facebook': 'Facebook',
      'login_apple': 'Apple',
      'login_guest': 'الدخول كضيف',
      'forgot_password': 'نسيت كلمة المرور؟',
      'home': 'الرئيسية',
      'rooms': 'الغرف',
      'posts': 'المنشورات',
      'messages': 'الرسائل',
      'profile': 'الملف الشخصي',
      'settings': 'الإعدادات',
      'search': 'بحث',
      'notifications': 'الإشعارات',
      'wallet': 'المحفظة',
      'vip': 'VIP',
      'store': 'المتجر',
      'vehicles': 'المركبات',
      'daily_tasks': 'المهام اليومية',
      'agencies': 'الوكالات',
      'friends': 'الأصدقاء',
      'followers': 'المتابعون',
      'following': 'متابَعون',
      'edit_profile': 'تعديل الملف الشخصي',
      'logout': 'تسجيل الخروج',
      'send': 'إرسال',
      'type_message': 'اكتب رسالة...',
      'create_post': 'منشور جديد',
      'publish': 'نشر',
      'what_to_say': 'ماذا تريد أن تقول؟',
      'no_posts': 'لا توجد منشورات بعد',
      'no_rooms': 'لا توجد غرف متاحة',
      'join': 'انضمام',
      'leave': 'مغادرة',
      'gift': 'هدية',
      'mute': 'كتم',
      'unmute': 'إلغاء الكتم',
      'block': 'حظر',
      'unblock': 'إلغاء الحظر',
      'kick': 'طرد',
      'ban': 'حظر من الغرفة',
      'admin': 'لوحة التحكم',
      'loading': 'جاري التحميل...',
      'error': 'حدث خطأ',
      'retry': 'إعادة المحاولة',
      'confirm': 'تأكيد',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'save': 'حفظ',
      'phone_number': 'رقم الهاتف',
      'send_otp': 'إرسال رمز التحقق',
      'verify': 'تحقق',
      'enter_otp': 'أدخل رمز التحقق',
      'new_password': 'كلمة المرور الجديدة',
      'recovery': 'استرداد الحساب',
      'recovery_email': 'أدخل بريدك الإلكتروني',
    },
    'en': {
      'app_name': 'LOVERS',
      'tagline': 'Connect without limits',
      'login_google': 'Sign in with Google',
      'login_phone': 'Phone',
      'login_facebook': 'Facebook',
      'login_apple': 'Apple',
      'login_guest': 'Guest Login',
      'forgot_password': 'Forgot password?',
      'home': 'Home',
      'rooms': 'Rooms',
      'posts': 'Posts',
      'messages': 'Messages',
      'profile': 'Profile',
      'settings': 'Settings',
      'search': 'Search',
      'notifications': 'Notifications',
      'wallet': 'Wallet',
      'vip': 'VIP',
      'store': 'Store',
      'vehicles': 'Vehicles',
      'daily_tasks': 'Daily Tasks',
      'agencies': 'Agencies',
      'friends': 'Friends',
      'followers': 'Followers',
      'following': 'Following',
      'edit_profile': 'Edit Profile',
      'logout': 'Logout',
      'send': 'Send',
      'type_message': 'Type a message...',
      'create_post': 'New Post',
      'publish': 'Publish',
      'what_to_say': 'What do you want to say?',
      'no_posts': 'No posts yet',
      'no_rooms': 'No rooms available',
      'join': 'Join',
      'leave': 'Leave',
      'gift': 'Gift',
      'mute': 'Mute',
      'unmute': 'Unmute',
      'block': 'Block',
      'unblock': 'Unblock',
      'kick': 'Kick',
      'ban': 'Ban from room',
      'admin': 'Admin Dashboard',
      'loading': 'Loading...',
      'error': 'An error occurred',
      'retry': 'Retry',
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'save': 'Save',
      'phone_number': 'Phone number',
      'send_otp': 'Send verification code',
      'verify': 'Verify',
      'enter_otp': 'Enter verification code',
      'new_password': 'New password',
      'recovery': 'Account Recovery',
      'recovery_email': 'Enter your email',
    },
  };

  static String t(String key, {String locale = 'ar'}) {
    return _translations[locale]?[key] ?? _translations['ar']?[key] ?? key;
  }

  static String tr(String key) {
    return t(key, locale: _currentLocale);
  }

  static String _currentLocale = 'ar';
  static void setLocale(String locale) {
    _currentLocale = locale;
  }
}
